#!/bin/sh

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    upgrade_sh=./upgrade-$branch.sh
    if test -e $upgrade_sh; then
        upgrade_sh=$(readlink $upgrade_sh)
        echo calling upgrade script: $upgrade_sh
        $upgrade_sh
    else
        echo NOT calling non-existent upgrade script: $upgrade_sh
    fi
done
